In [1]:
import mysql.connector

print("MySQL Connector is working!")

MySQL Connector is working!

In [3]:
import pandas as pd
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="RKit_007",
    database="mysql"
)

query = "SELECT * FROM user"

df = pd.read_sql(query, conn)

df.head()

/var/folders/vp/x0b_dx0x7mlczcd47twtwvgh0000gn/T/ipykernel_2979/4156214297.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,Host,User,Select_priv,Insert_priv,Update_priv,Delete_priv,Create_priv,Drop_priv,Reload_priv,Shutdown_priv,...,password_expired,password_last_changed,password_lifetime,account_locked,Create_role_priv,Drop_role_priv,Password_reuse_history,Password_reuse_time,Password_require_current,User_attributes
0,localhost,mysql.infoschema,Y,N,N,N,N,N,N,N,...,N,2026-08-07 17:50:51,None,Y,N,N,None,None,None,None
1,localhost,mysql.session,N,N,N,N,N,N,N,Y,...,N,2026-08-07 17:50:51,None,Y,N,N,None,None,None,None
2,localhost,mysql.sys,N,N,N,N,N,N,N,N,...,N,2026-08-07 17:50:51,None,Y,N,N,None,None,None,None
3,localhost,root,Y,Y,Y,Y,Y,Y,Y,Y,...,N,2026-08-07 17:50:53,None,N,Y,Y,None,None,None,None

In [4]:
df

,Host,User,Select_priv,Insert_priv,Update_priv,Delete_priv,Create_priv,Drop_priv,Reload_priv,Shutdown_priv,...,password_expired,password_last_changed,password_lifetime,account_locked,Create_role_priv,Drop_role_priv,Password_reuse_history,Password_reuse_time,Password_require_current,User_attributes
0,localhost,mysql.infoschema,Y,N,N,N,N,N,N,N,...,N,2026-08-07 17:50:51,None,Y,N,N,None,None,None,None
1,localhost,mysql.session,N,N,N,N,N,N,N,Y,...,N,2026-08-07 17:50:51,None,Y,N,N,None,None,None,None
2,localhost,mysql.sys,N,N,N,N,N,N,N,N,...,N,2026-08-07 17:50:51,None,Y,N,N,None,None,None,None
3,localhost,root,Y,Y,Y,Y,Y,Y,Y,Y,...,N,2026-08-07 17:50:53,None,N,Y,Y,None,None,None,None

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 51 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Host                      4 non-null      object
 1   User                      4 non-null      object
 2   Select_priv               4 non-null      object
 3   Insert_priv               4 non-null      object
 4   Update_priv               4 non-null      object
 5   Delete_priv               4 non-null      object
 6   Create_priv               4 non-null      object
 7   Drop_priv                 4 non-null      object
 8   Reload_priv               4 non-null      object
 9   Shutdown_priv             4 non-null      object
 10  Process_priv              4 non-null      object
 11  File_priv                 4 non-null      object
 12  Grant_priv                4 non-null      object
 13  References_priv           4 non-null      object
 14  Index_priv                4 non-null      object
 15  Alter_priv                4 non-null      object
 16  Show_db_priv              4 non-null      object
 17  Super_priv                4 non-null      object
 18  Create_tmp_table_priv     4 non-null      object
 19  Lock_tables_priv          4 non-null      object
 20  Execute_priv              4 non-null      object
 21  Repl_slave_priv           4 non-null      object
 22  Repl_client_priv          4 non-null      object
 23  Create_view_priv          4 non-null      object
 24  Show_view_priv            4 non-null      object
 25  Create_routine_priv       4 non-null      object
 26  Alter_routine_priv        4 non-null      object
 27  Create_user_priv          4 non-null      object
 28  Event_priv                4 non-null      object
 29  Trigger_priv              4 non-null      object
 30  Create_tablespace_priv    4 non-null      object
 31  ssl_type                  4 non-null      object
 32  ssl_cipher                4 non-null      object
 33  x509_issuer               4 non-null      object
 34  x509_subject              4 non-null      object
 35  max_questions             4 non-null      int64
 36  max_updates               4 non-null      int64
 37  max_connections           4 non-null      int64
 38  max_user_connections      4 non-null      int64
 39  plugin                    4 non-null      object
 40  authentication_string     4 non-null      object
 41  password_expired          4 non-null      object
 42  password_last_changed     4 non-null      datetime64[ns]
 43  password_lifetime         0 non-null      object
 44  account_locked            4 non-null      object
 45  Create_role_priv          4 non-null      object
 46  Drop_role_priv            4 non-null      object
 47  Password_reuse_history    0 non-null      object
 48  Password_reuse_time       0 non-null      object
 49  Password_require_current  0 non-null      object
 50  User_attributes           0 non-null      object
dtypes: datetime64[ns](1), int64(4), object(46)
memory usage: 1.7+ KB

In [6]:
df.describe()

,max_questions,max_updates,max_connections,max_user_connections,password_last_changed
count,4.0,4.0,4.0,4.0,4
mean,0.0,0.0,0.0,0.0,2026-08-07 17:50:51.499999744
min,0.0,0.0,0.0,0.0,2026-08-07 17:50:51
25%,0.0,0.0,0.0,0.0,2026-08-07 17:50:51
50%,0.0,0.0,0.0,0.0,2026-08-07 17:50:51
75%,0.0,0.0,0.0,0.0,2026-08-07 17:50:51.500000
max,0.0,0.0,0.0,0.0,2026-08-07 17:50:53
std,0.0,0.0,0.0,0.0,NaN

In [7]:
df.shape

(4, 51)

In [8]:
df.isnull().sum()

Host                        0
User                        0
Select_priv                 0
Insert_priv                 0
Update_priv                 0
Delete_priv                 0
Create_priv                 0
Drop_priv                   0
Reload_priv                 0
Shutdown_priv               0
Process_priv                0
File_priv                   0
Grant_priv                  0
References_priv             0
Index_priv                  0
Alter_priv                  0
Show_db_priv                0
Super_priv                  0
Create_tmp_table_priv       0
Lock_tables_priv            0
Execute_priv                0
Repl_slave_priv             0
Repl_client_priv            0
Create_view_priv            0
Show_view_priv              0
Create_routine_priv         0
Alter_routine_priv          0
Create_user_priv            0
Event_priv                  0
Trigger_priv                0
Create_tablespace_priv      0
ssl_type                    0
ssl_cipher                  0
x509_issuer                 0
x509_subject                0
max_questions               0
max_updates                 0
max_connections             0
max_user_connections        0
plugin                      0
authentication_string       0
password_expired            0
password_last_changed       0
password_lifetime           4
account_locked              0
Create_role_priv            0
Drop_role_priv              0
Password_reuse_history      4
Password_reuse_time         4
Password_require_current    4
User_attributes             4
dtype: int64